--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/kaidoMC/ItemFactory
build-by-default: true
branches:
- master
projects:
  ItemFactory:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: 2.1.1
      - src: NhanAZ/libBedrock/libBedrock
        version: 1.0.0
...
