---
name: ItemFactory
version: 1.0.0
author: kaidoMC
api: [3.0.0, 3.22.5]
main: kaidoMC\ItemFactory\Loader
website: https://github.com/kaidoMC
description: Create, edit, copy items of your choice.
commands:
  itemfactory:
    aliases: [ifa]
    permission: itemfactory.use
    description: "Create, edit, copy items of your choice."
    usage: "/itemfactory or /ifa - Open the ItemFactory management interface"
    permission-message: "§r§cYou do not have permission to use this feature!§r"
permissions:
  itemfactory.use:
    default: op
    description: "Permissions allow create, edit, copy items of your choice."
...
