---
name: ItemFactory
version: 1.0.2
author: kaidoMC
api: [5.0.0]
main: kaidoMC\ItemFactory\Loader
website: https://github.com/kaidoMC
commands:
  ifa:
    permission: ifa.use
    description: "Create, edit, copy items of your choice."
    usage: "/ifa - Open the ItemFactory management interface"
permissions:
  ifa.use:
    default: op
    description: "Permissions allow create, edit, copy items of your choice."
...